name: "LZ4 1.10.0 Update"
description: "Apply LZ4 1.10.0 OPlus Patch Update"

inputs:
  lz4-neon:
    description: "Selected LZ4 1.10.0 Patch"
    required: true
    default: ""

runs:
  using: composite

  steps:
    - name: 🔧 LZ4 1.10.0 Update
      if: ${{ inputs.zram-custom-patch == 'LZ4-1.10.0-Patch-Update' }}
      shell: bash
      run: |
        set -euo pipefail

        ZRAMPATCH="${{ inputs.zram-custom-patch }}"

        KCDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"

        LZ4PATCHUPDATE="${GITHUB_WORKSPACE}/kernel_workspace/lz4_oplus"

        echo "🚀 LZ4 1.10.0 Patch Update"
        echo "📦 Patch Type : $ZRAMPATCH"
        echo ""

        if [[ ! -d "$KCDIR" ]]; then
          echo "⚠️ Kernel Common Directory Not Found"
          exit 0
        fi

        cd "$KCDIR"

        if [[ ! -f "${LZ4PATCHUPDATE}/apply_lz4_oplus.sh" ]]; then
          echo "⚠️ LZ4 OPlus Shell Script File Not Found"
          exit 1
        fi

        echo "🚀 Running LZ4 Patch Update Script..."
        . "${LZ4PATCHUPDATE}/apply_lz4_oplus.sh"
        echo "✔️ LZ4 OPlus Shell Script File Completed"

        source "$REJECTCHECKER"
        checkrejects .

        echo ""
        echo "🎉 LZ4 1.10.0 Patch Update Completed"
        echo "📦 Patch Type : $ZRAMPATCH"
