name: "LZ4 1.10.0 Update"
description: "Apply LZ4 1.10.0 OPlus Patch Update"

inputs:
  # Selected LZ4 1.10.0 Patch
  lz4-neon:
    description: "Selected LZ4 1.10.0 Patch"
    required: true
    default: ""

runs:
  using: composite

  steps:
    - name: 🔧 LZ4 1.10.0 Update
      # Apply only when LZ4 1.10.0 Patch Update is selected
      if: ${{ inputs.lz4-neon == 'LZ4-1.10.0-Patch-Update' }}
      shell: bash
      run: |
        set -euo pipefail

        # Selected Patch Type
        ZRAMPATCH="${{ inputs.lz4-neon }}"

        # Main Kernel Common Directory
        KCDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"

        # LZ4 Update Script Repository
        LZ4PATCHUPDATE="${GITHUB_WORKSPACE}/kernel_workspace/lz4_oplus"

        echo "🚀 LZ4 1.10.0 Patch Update"
        echo "📦 Patch Type : $ZRAMPATCH"
        echo ""

        # Validate Kernel Source Directory
        if [[ ! -d "$KCDIR" ]]; then
          echo "⚠️ Kernel Common Directory Not Found"
          exit 0
        fi

        # Move Into Kernel Source Directory
        cd "$KCDIR"

        # Ensure Updater Script Exists
        if [[ ! -f "${LZ4PATCHUPDATE}/apply_lz4_oplus.sh" ]]; then
          echo "⚠️ LZ4 OPlus Shell Script File Not Found"
          exit 1
        fi

        # Execute LZ4 Update Script
        echo "🚀 Running LZ4 Patch Update Script..."
        . "${LZ4PATCHUPDATE}/apply_lz4_oplus.sh"
        echo "✔️ LZ4 OPlus Shell Script File Completed"

        # Load Reject Checker and Run Rejection Check
        source "$REJECTCHECKER"
        checkrejects .

        echo ""
        echo "🎉 LZ4 1.10.0 Patch Update Completed"
        echo "📦 Patch Type : $ZRAMPATCH"
