name: 📄 Resolve Manifest File Configuration
description: Resolve Device Name to Manifest Configuration Filename
inputs:
  FILE:
    description: Device Mame
    required: true
outputs:
  file:
    description: Resolved Manifest Configuration Filename
    value: ${{ steps.resolve-file.outputs.file }}
runs:
  using: composite
  steps:
    - name: 📄 Resolve Manifest Configuration
      id: resolve-file
      shell: bash
      env:
        INPUTFILE: ${{ inputs.FILE }}
      run: |
        set -Eeuo pipefail
        case "$INPUTFILE" in
          1+10Pro)           FILE="oneplus_10_pro_b" ;;
          1+10T)             FILE="oneplus_10t_v" ;;
          1+11R)             FILE="oneplus_11r_b" ;;
          1+Ace2)            FILE="oneplus_ace2_b" ;;
          1+11)              FILE="oneplus_11_b" ;;
          1+12R)             FILE="oneplus_12r_b" ;;
          1+PadLite)         FILE="oneplus_pad_lite_b" ;;
          1+Ace2Pro)         FILE="oneplus_ace2_pro_b" ;;
          1+Ace3)            FILE="oneplus_ace3_b" ;;
          1+Open)            FILE="oneplus_open_b" ;;
          1+NordCE4)         FILE="oneplus_nord_ce4_b" ;;
          1+NordCE4Lite5G)   FILE="oneplus_nord_ce4_lite_5g_b" ;;
          1+Nord4)           FILE="oneplus_nord_4_b" ;;
          1+Ace3V)           FILE="oneplus_ace_3v_b" ;;
          1+12)              FILE="oneplus_12_b" ;;
          1+12-Custom)       FILE="oneplus_12_custom" ;;
          1+13R)             FILE="oneplus_13r_b" ;;
          1+Ace3Pro)         FILE="oneplus_ace3_pro_b" ;;
          1+Ace5)            FILE="oneplus_ace5_b" ;;
          1+PadPro)          FILE="oneplus_pad_pro_b" ;;
          1+Pad2)            FILE="oneplus_pad2_b" ;;
          1+Nord5)           FILE="oneplus_nord_5_b" ;;
          1+Ace5Pro)         FILE="oneplus_ace5_pro_b" ;;
          1+13-China)        FILE="oneplus_13_china" ;;
          1+13)              FILE="oneplus_13_b" ;;
          1+13-Custom)       FILE="oneplus_13_custom" ;;
          1+13-Wild)         FILE="oneplus_13_wild" ;;
          1+13T)             FILE="oneplus_13t_b" ;;
          1+13S)             FILE="oneplus_13s_b" ;;
          1+Pad2Pro)         FILE="oneplus_pad_2_pro_b" ;;
          1+Pad3)            FILE="oneplus_pad_3_b" ;;
          1+Ace6)            FILE="oneplus_ace_6" ;;
          1+Turbo6)          FILE="oneplus_turbo_6" ;;
          1+Nord6)           FILE="oneplus_nord_6" ;;
          1+Ace6T)           FILE="oneplus_ace_6t" ;;
          1+Ace6T-Canary)    FILE="oneplus_ace_6t_canary" ;;
          1+15R)             FILE="oneplus_15r" ;;
          1+15R-Canary)      FILE="oneplus_15r_canary" ;;
          1+15)              FILE="oneplus_15" ;;
          1+15-Canary)       FILE="oneplus_15_canary" ;;
          1+15-Custom)       FILE="oneplus_15_custom" ;;
          1+15T)             FILE="oneplus_15t" ;;
          1+15T-Canary)      FILE="oneplus_15t_canary" ;;
          1+Pad3Pro-Canary)  FILE="oneplus_pad3_pro_canary" ;;
          1+Pad4)            FILE="oneplus_pad_4" ;;
          1+Pad4-Canary)     FILE="oneplus_pad_4_canary" ;;
          *)
            echo "⚠️ Unsupported File: $INPUTFILE"
            exit 1
            ;;
        esac
        echo "FILE=$FILE" >> "$GITHUB_ENV"
        echo "file=$FILE" >> "$GITHUB_OUTPUT"
        echo "└─ 📄 Selected File : $INPUTFILE"
        echo "└─ 📄 Resolved File : $FILE"
