name: AOSP SM-8750

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: 'KernelSU Next'
        required: true
        type: choice
        default: 'ksunext'
        options:
          - 'ksunext'
          - 'none'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Kernel AOSP SM-8750 by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      CLANG_VERSION: clang-r547379

    steps:

    - uses: actions/checkout@v6

    - name: Swap Disk Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup Build Tools
      run: |
        echo "BUILD_TIME=$(date +%y%m%d)" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y git dwarves libelf-dev ccache automake flex bison build-essential \
          zlib1g-dev libncurses5-dev libc6-dev-i386 bc device-tree-compiler python3 make

        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Cache Clang
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/kernel_workspace/clang-aosp
        key: ${{ env.CLANG_VERSION }}

    - name: Download Clang
      if: steps.cache-clang.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir -p clang-aosp
        wget -O clang.tar.gz \
          https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/${CLANG_VERSION}.tar.gz
        tar -C clang-aosp -xzf clang.tar.gz

    - name: Clone Kernel Source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace

        git clone --recursive \
          https://github.com/LineageOS/android_kernel_oneplus_sm8750 \
          -b lineage-23.2 sm8750 --depth=1

        git clone --recursive \
          https://github.com/LineageOS/android_kernel_oneplus_sm8750-modules \
          -b lineage-23.2 sm8750-modules --depth=1

    - name: Setup KernelSU-Next
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/sm8750

        if [[ "${{ github.event.inputs.ksu_type }}" == "ksunext" ]]; then

          echo "Installing KernelSU-Next..."

          curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh | bash -s dev

          # Ensure Directory Exists
          if [ ! -d "KernelSU-Next" ]; then
            echo "KernelSU-Next Missing, Creating Fallback Directory..."

            git clone https://github.com/KernelSU-Next/KernelSU-Next -b dev KernelSU-Next
          fi

          cd KernelSU-Next

          KSU_VERSION=$(git rev-list --count HEAD)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV

        else
          echo "KernelSU disabled"
        fi

    - name: Setup SUSFS
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/sm8750

        git clone --depth=1 -b gki-android15-6.6 \
          https://gitlab.com/simonpunk/susfs4ksu.git

        # KernelSU Patch
        cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU-Next/
        cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch .

        # Kernel FS Patches
        cp -r susfs4ksu/kernel_patches/fs/* fs/
        cp -r susfs4ksu/kernel_patches/include/linux/* include/linux/

        cd KernelSU-Next
        
        patch -p1 < 10_enable_susfs_for_ksu.patch || echo "KSU patch failed"

        cd ..
        
        patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || echo "Kernel SUSFS patch failed"

    - name: Wild Patches
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/sm8750/KernelSU-Next

        git clone https://github.com/Liam314839/wildpatches

        echo "Applying Wild Patches..."

        for patch in wildpatches/*.patch; do
          echo "Applying $patch"

          if patch -p1 < "$patch"; then
            echo "OK: $patch"
          else
            echo "WARNING: Failed $patch"
          fi
        done

    - name: Inject Kernel Configurations
      run: |
        CONFIG="kernel_workspace/sm8750/arch/arm64/configs/vendor/oplus/sun_perf.config"

        echo "CONFIG_DODGE_DTB=y" >> $CONFIG
        echo "CONFIG_KSU=y" >> $CONFIG
        echo "CONFIG_KSU_SUSFS=y" >> $CONFIG  

    - name: Build Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/sm8750

        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH

        make O=out gki_defconfig vendor/sun_perf.config vendor/oplus/sun_perf.config
        make -j$(nproc) O=out

    - name: Check Image
      run: |
        test -f kernel_workspace/sm8750/out/arch/arm64/boot/Image || exit 1

    - name: AnyKernel3
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace

        git clone https://github.com/AndreiMikh/AnyKernel3
        rm -rf AnyKernel3/.git

        cp sm8750/out/arch/arm64/boot/Image AnyKernel3/

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: SM8750-KSU-${{ env.KSUVER }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/AnyKernel3/*
